import { Announcement } from '../types';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'cand-1',
    candidateId: 'C2026-001',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=C2026-001',
    fullName: 'Ahmed Mohamed',
    gender: 'Male',
    partyName: 'MDP',
    position: 'Council President',
    status: 'Active',
    totalVotes: 1250,
  },
  {
    id: 'cand-2',
    candidateId: 'C2026-002',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=C2026-002',
    fullName: 'Fathimath Ali',
    gender: 'Female',
    partyName: 'PPM',
    position: 'Council President',
    status: 'Active',
    totalVotes: 1100,
  },
  {
    id: 'cand-3',
    candidateId: 'C2026-003',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=C2026-003',
    fullName: 'Ibrahim Hassan',
    gender: 'Male',
    partyName: 'Independent',
    position: 'Council Member',
    status: 'Withdrawn',
    totalVotes: 0,
  },
  {
    id: 'cand-4',
    candidateId: 'C2026-004',
    profilePhotoUrl: 'https://i.pravatar.cc/150?u=C2026-004',
    fullName: 'Aishath Ibrahim',
    gender: 'Female',
    partyName: 'JP',
    position: 'Council Member',
    status: 'Active',
    totalVotes: 980,
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: '1',
    title: 'Polling Station Time Updated',
    content: 'The official guidelines for the upcoming election day have been released. Please review the attached document for detailed procedures regarding polling station setup, voter verification, and ballot counting.',
    category: 'Urgent',
    author: 'Admin',
    date: new Date('2026-03-25').toISOString(),
    isPinned: true,
    isUrgent: true,
  },
  {
    id: '2',
    title: 'Voter Registration Deadline Extended',
    content: 'Due to high demand, the voter registration deadline has been extended by 48 hours. Ensure all pending applications are processed by the new cutoff time.',
    category: 'General',
    author: 'Registrar',
    date: new Date('2026-02-18').toISOString(),
    isPinned: false,
    isUrgent: false,
  },
  {
    id: '3',
    title: 'Staff Training Session',
    content: 'A mandatory training session for all polling station staff will be held this Saturday at the Community Hall. Attendance is required for certification.',
    category: 'Election Day',
    author: 'HR Dept',
    date: new Date('2026-02-15').toISOString(),
    isPinned: false,
    isUrgent: false,
  },
  {
    id: '4',
    title: 'System Maintenance Scheduled',
    content: 'The voter database will undergo scheduled maintenance on Sunday from 2:00 AM to 4:00 AM. Access will be temporarily unavailable during this window.',
    category: 'System Update',
    author: 'IT Support',
    date: new Date('2026-02-10').toISOString(),
    isPinned: false,
    isUrgent: false,
  },
];
